from colorama import Fore, Back

IDENTIFIER = {}
IDENTIFIER['shield'] = {}
IDENTIFIER['shield']['unavailable'] = 0
IDENTIFIER['shield']['available'] = 1
IDENTIFIER['shield']['in_use'] = 2

DIMENSION = {}
DIMENSION['length'] = 30
DIMENSION['width'] = 1500
DIMENSION['frame_width'] = 150
DIMENSION['sky_height'] = 3
DIMENSION['ground_height'] = 4
DIMENSION['cloud'] = {}
DIMENSION['cloud']['x'] = 4
DIMENSION['cloud']['y'] = 12
DIMENSION['mountain'] = {}
DIMENSION['mountain']['x'] = 8
DIMENSION['mountain']['y'] = 54
DIMENSION['tree'] = {}
DIMENSION['tree']['x'] = 11
DIMENSION['tree']['y'] = 30
DIMENSION['Mandalorian'] = {}
DIMENSION['Mandalorian']['x'] = 3
DIMENSION['Mandalorian']['y'] = 3
DIMENSION['Mandalorian_dragon'] = {}
DIMENSION['Mandalorian_dragon']['x'] = 10
DIMENSION['Mandalorian_dragon']['y'] = 37
DIMENSION['slave_enemy'] = {}
DIMENSION['slave_enemy']['x'] = 3
DIMENSION['slave_enemy']['y'] = 3
DIMENSION['boss_enemy'] = {}
DIMENSION['boss_enemy']['x'] = 7
DIMENSION['boss_enemy']['y'] = 36
DIMENSION['boss_enemy']['mouth'] = 5
DIMENSION['fire_beam-1'] = {}
DIMENSION['fire_beam-1']['x'] = 5
DIMENSION['fire_beam-1']['y'] = 6
DIMENSION['fire_beam-2'] = {}
DIMENSION['fire_beam-2']['x'] = 5
DIMENSION['fire_beam-2']['y'] = 6
DIMENSION['fire_beam-3'] = {}
DIMENSION['fire_beam-3']['x'] = 2
DIMENSION['fire_beam-3']['y'] = 6
DIMENSION['fire_beam-4'] = {}
DIMENSION['fire_beam-4']['x'] = 5
DIMENSION['fire_beam-4']['y'] = 2
DIMENSION['magnet'] = {}
DIMENSION['magnet']['x'] = 3
DIMENSION['magnet']['y'] = 6
DIMENSION['dragon_dim'] = {}
DIMENSION['dragon_dim']['x'] = 4
DIMENSION['dragon_dim']['y'] = 30

COLOR = {}
COLOR['Mandalorian_normal'] = Fore.WHITE
COLOR['Mandalorian_shield'] = Fore.GREEN
COLOR['slave_enemy'] = Fore.CYAN
COLOR['boss_enemy'] = Fore.YELLOW
COLOR['ground'] = Back.RED
COLOR['sky'] = Back.BLUE
COLOR['cloud'] = Fore.BLUE
COLOR['mountain'] = Fore.MAGENTA
COLOR['tree'] = Fore.GREEN
COLOR['fire_beam'] = Fore.RED
COLOR['magnet-1'] = Fore.BLUE
COLOR['magnet-2'] = Fore.RED
COLOR['powerup'] = Fore.CYAN
COLOR['dragon_powerup'] = Fore.RED
COLOR['bullet'] = Fore.YELLOW
COLOR['iceball'] = Fore.WHITE
COLOR['coin'] = Fore.YELLOW
COLOR['fire'] = Fore.RED

PATH = {}
PATH['clouds'] = './ascii/background/clouds.txt'
PATH['mountain'] = './ascii/background/mountain.txt'
PATH['tree'] = './ascii/background/tree.txt'
PATH['Mandalorian'] = './ascii/characters/mandalorian.txt'
PATH['slave_enemy'] = './ascii/characters/slave_enemy.txt'
PATH['boss_enemy-1'] = './ascii/characters/boss_enemy/boss_enemy1.txt'
PATH['boss_enemy-2'] = './ascii/characters/boss_enemy/boss_enemy2.txt'
PATH['magnet'] = './ascii/obstacles/magnet.txt'
PATH['fire_beam-1'] ='./ascii/obstacles/fire_beam/fire_beam-1.txt'
PATH['fire_beam-2'] ='./ascii/obstacles/fire_beam/fire_beam-2.txt'
PATH['fire_beam-3'] ='./ascii/obstacles/fire_beam/fire_beam-3.txt'
PATH['fire_beam-4'] ='./ascii/obstacles/fire_beam/fire_beam-4.txt'
PATH['congrats'] = './ascii/extras/congrats.txt'
PATH['game_over'] = './ascii/extras/game_over.txt'
PATH['time_up'] = './ascii/extras/time_up.txt'
PATH['dragon'] = './ascii/characters/dragon.txt'

INIT_PLACE = {}
INIT_PLACE['Mandalorian'] = {}
INIT_PLACE['Mandalorian']['x'] = DIMENSION['length'] - DIMENSION['ground_height'] - DIMENSION['Mandalorian']['x']
INIT_PLACE['Mandalorian']['y'] = 10
INIT_PLACE['slave_enemy'] = {}
INIT_PLACE['slave_enemy']['x'] = DIMENSION['length']-DIMENSION['ground_height']-DIMENSION['slave_enemy']['x']
INIT_PLACE['slave_enemy']['y'] = 0
INIT_PLACE['boss_enemy'] = {}
INIT_PLACE['boss_enemy']['x'] = DIMENSION['sky_height']
INIT_PLACE['boss_enemy']['y'] = DIMENSION['width'] - DIMENSION['boss_enemy']['y']

TOPBAR = {}
TOPBAR['game_time'] = 500
TOPBAR['mando_lives'] = 5
TOPBAR['viserion_lives'] = 50
TOPBAR['shield_activation_time'] = 60
TOPBAR['shield_remaining_time'] = 10

MANDO_MOVES_WITH_FRAME = False
MANDO_MOVES_FASTER_SPEED = False